"""AI Data Analyst Agent package."""

from analyst.analysis import (
    AGGREGATIONS,
    OPERATORS,
    PERIODS,
    AnalysisResult,
    Condition,
    correlation,
    describe_numeric,
    filter_rows,
    group_aggregate,
    group_by_period,
    sort_rows,
    value_counts,
)
from analyst.agent import (
    DEFAULT_MAX_STEPS,
    Answer,
    EvidenceStep,
    answer_question,
)
from analyst.charts import (
    bar_chart,
    box_plot,
    correlation_heatmap,
    figure_to_png_bytes,
    histogram,
    line_chart,
    scatter_plot,
)
from analyst.context import ColumnSummary, DatasetContext, build_context
from analyst.conversation import DEFAULT_HISTORY_TURNS, Conversation, Turn
from analyst.errors import (
    AnalysisError,
    ColumnNotFoundError,
    DatasetError,
    DatasetNotFoundError,
    DatasetReadError,
    EmptyDatasetError,
    InvalidOperationError,
    InvalidToolArgumentsError,
    LLMConfigurationError,
    LLMError,
    LLMProviderError,
    LLMResponseError,
    ToolError,
    UnknownToolError,
    UnsupportedFileTypeError,
)
from analyst.gemini import GeminiClient
from analyst.grounding import GroundingReport, check_grounding
from analyst.groq import GroqClient
from analyst.llm import (
    DEFAULT_GROQ_MODEL,
    DEFAULT_MODEL,
    PROVIDERS,
    LLMClient,
    LLMConfig,
    ProviderSettings,
    create_client,
    get_provider_settings,
    load_config,
    resolve_provider,
)
from analyst.loader import load_dataset
from analyst.profiling import (
    CategoricalStats,
    ColumnProfile,
    DatasetProfile,
    DatetimeColumn,
    NumericStats,
    profile_dataset,
)
from analyst.tools import (
    ACTIONS,
    CLARIFY,
    TOOLS,
    ToolRequest,
    ToolSpec,
    describe_tools,
    get_tool,
    run_tool,
    tool_names,
)
from analyst.validation import SUPPORTED_EXTENSIONS

__version__ = "0.1.0"

__all__ = [
    "ACTIONS",
    "AGGREGATIONS",
    "AnalysisError",
    "AnalysisResult",
    "Answer",
    "CLARIFY",
    "CategoricalStats",
    "ColumnNotFoundError",
    "ColumnProfile",
    "ColumnSummary",
    "Condition",
    "Conversation",
    "DEFAULT_GROQ_MODEL",
    "DEFAULT_HISTORY_TURNS",
    "DEFAULT_MAX_STEPS",
    "DEFAULT_MODEL",
    "DatasetContext",
    "DatasetError",
    "DatasetNotFoundError",
    "DatasetProfile",
    "DatasetReadError",
    "DatetimeColumn",
    "EmptyDatasetError",
    "EvidenceStep",
    "GeminiClient",
    "GroqClient",
    "GroundingReport",
    "InvalidOperationError",
    "InvalidToolArgumentsError",
    "LLMClient",
    "LLMConfig",
    "LLMConfigurationError",
    "LLMError",
    "LLMProviderError",
    "LLMResponseError",
    "NumericStats",
    "OPERATORS",
    "PERIODS",
    "PROVIDERS",
    "ProviderSettings",
    "SUPPORTED_EXTENSIONS",
    "TOOLS",
    "ToolError",
    "ToolRequest",
    "ToolSpec",
    "Turn",
    "UnknownToolError",
    "UnsupportedFileTypeError",
    "answer_question",
    "bar_chart",
    "box_plot",
    "build_context",
    "check_grounding",
    "correlation",
    "correlation_heatmap",
    "create_client",
    "describe_numeric",
    "describe_tools",
    "figure_to_png_bytes",
    "filter_rows",
    "get_provider_settings",
    "get_tool",
    "group_aggregate",
    "group_by_period",
    "histogram",
    "line_chart",
    "load_config",
    "load_dataset",
    "profile_dataset",
    "resolve_provider",
    "run_tool",
    "scatter_plot",
    "sort_rows",
    "tool_names",
    "value_counts",
]
